### ISSUE TITLE
Implement wallet API support

### ISSUE THREAD

**Issue by educare-kumapuru** [VaniThapar/UnityLend#13]
1. Create dao class for Wallet
2. Force 1:1 mapping of User with wallet
3. Add support to fetch wallet details with the help of User Id 
4. Wallet should have debit and credit functionality
5. Wallet balance should not go less than 0;
6. User can load the money into wallet (For now user will just go ahead and update the wallet amount)
7. Track debit and credit ledger for wallet
8. Provide functionality to fetch all the credit and debit records for a given user wallet

**Comment by SURABHI2003** [comment]
Wallet API has been implemented and reviewed by us. We are waiting for you to review it.
